language: node_js
node_js:
  - "18"
dist: focal
script:
  - npm test

deploy:
  provider: pages
  token: $toki
  keep_history: true
  local_dir: build
  on:
    branch: main

before_install:
  - nvm install 18
  - nvm use 18
install:
<<<<<<< HEAD
  - npm install
=======
  - npm install
>>>>>>> origin/101441732-civan
